name: 'action-clear'
author: 'hocgin'
description: '清理项目一些信息(tags/releases)'
inputs:
  debug:
    required: false
    description: 'debug mode'
  limit_tags:
    required: false
    default: '-1'
    description: '保留最后 tags 数量，-1 全保留'
  limit_release:
    required: false
    default: '-1'
    description: '保留最后 release 数量，-1 全保留'
  limit_err_workflow:
    required: false
    default: '-1'
    description: '保留最后 workflow 错误日志数量，-1 全保留'
#outputs:
runs:
  using: node16
  main: dist/index.js
