name: 'action-starter'
author: 'hocgin'
description: '项目描述信息'
inputs:
  debug:
    required: false
    description: 'debug mode'
  limit_tags:
    required: false
    default: '-1'
    description: '保留最后 tags 数量，-1 全保留'
  limit_release:
    required: false
    default: '-1'
    description: '保留最后 release 数量，-1 全保留'
#outputs:
runs:
  using: node16
  main: dist/index.js
